"""PDF report generator for LungAI analysis results."""

import re
from fpdf import FPDF


def _safe(text: str) -> str:
    """Replace non-latin-1 characters so fpdf2 can encode them."""
    replacements = {
        "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "-", "\u2026": "...", "\u2022": "-",
        "\u00a0": " ", "\u00b0": " deg", "\u00d7": "x", "\u00f7": "/",
        "\u2010": "-", "\u2011": "-", "\u2012": "-", "\u2015": "-",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    text = re.sub(r"[^\x00-\xff]", "?", text)
    return text


class LungAIReport(FPDF):
    """Custom PDF report for pneumonia CDSS analysis."""

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(10, 22, 40)
        self.cell(0, 10, "LungAI - Chest X-Ray Analysis Report", 0, 1, "C")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, "Multi-Agent Pneumonia Clinical Decision Support System", 0, 1, "C")
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Generated by LungAI CDSS", 0, 0, "C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(10, 22, 40)
        self.cell(0, 8, _safe(title), 0, 1)
        self.set_draw_color(10, 22, 40)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(40, 40, 40)
        self.multi_cell(0, 5, _safe(text))
        self.ln(2)

    def key_value(self, key: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(40, 40, 40)
        self.cell(55, 6, _safe(key) + ":")
        self.set_font("Helvetica", "", 10)
        self.cell(0, 6, _safe(value), 0, 1)

    def bullet_list(self, items: list[str]):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(40, 40, 40)
        for item in items:
            self.cell(5, 5, "-")
            self.multi_cell(0, 5, _safe(f" {item}"))
            self.ln(1)


def generate_report(results: dict) -> bytes:
    """Generate a PDF report from the pipeline frontend result dict. Returns bytes."""
    pdf = LungAIReport()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Case info
    pdf.section_title("Case Information")
    pdf.key_value("Case ID", str(results.get("case_id", "N/A")))
    pdf.key_value("Image Quality", str(results.get("imageQuality", "N/A")))
    pdf.key_value("Processing Time", f"{results.get('processingTime', 0):.1f}s")
    pdf.key_value("Validation", "Passed" if results.get("isValidated") else "Failed")
    pdf.ln(4)

    # Diagnosis
    pdf.section_title("Diagnosis")
    pdf.key_value("Prediction", str(results.get("prediction", "Unknown")))
    conf = results.get("confidence", 0)
    pdf.key_value("Confidence", f"{conf}%")
    pdf.ln(2)

    probs = results.get("probabilities", {})
    if probs:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Class Probabilities:", 0, 1)
        pdf.set_font("Helvetica", "", 10)
        for cls in ["normal", "bacterial", "viral"]:
            val = probs.get(cls, 0)
            pdf.cell(10, 5, "")
            pdf.cell(0, 5, f"{cls.title()}: {val * 100:.1f}%", 0, 1)
        pdf.ln(2)

    # Detected regions
    regions = results.get("regions", [])
    if regions:
        pdf.section_title("Detected Regions")
        for r in regions:
            severity = r.get("severity", "")
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(40, 40, 40)
            pdf.cell(0, 6, f"{r.get('name', 'Finding')} [{severity}]", 0, 1)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(80, 80, 80)
            pdf.multi_cell(0, 5, _safe(r.get("description", "")))
            pdf.ln(2)

    # Clinical summary
    summary = results.get("summary", "")
    if summary:
        pdf.section_title("Clinical Summary")
        pdf.body_text(summary)

    # Recommendations
    recs = results.get("recommendations", [])
    if recs:
        pdf.section_title("Recommendations")
        pdf.bullet_list(recs)

    # Evidence sources
    report_data = results.get("report", {})
    sources = report_data.get("sources", [])
    if sources:
        pdf.add_page()
        pdf.section_title("Evidence Sources")
        for i, src in enumerate(sources, 1):
            journal = src.get("journal", "PubMed")
            year = src.get("year", "N/A")
            title = src.get("title", "")
            text = src.get("text", "")
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(40, 40, 40)
            pdf.cell(0, 6, _safe(f"{i}. {title}"), 0, 1)
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(0, 5, _safe(f"Source: {journal} | Year: {year}"), 0, 1)
            if text:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(60, 60, 60)
                pdf.multi_cell(0, 5, _safe(text[:600]))
            pdf.ln(3)

    # Disclaimer
    pdf.add_page()
    pdf.section_title("Disclaimer")
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5, _safe(
        "This report is generated by an AI-assisted Clinical Decision Support System (CDSS) "
        "and is intended for informational and educational purposes only. It does NOT constitute "
        "medical advice, diagnosis, or treatment. All findings should be reviewed and confirmed "
        "by a qualified healthcare professional. The model predictions are probabilistic and "
        "may contain errors. Clinical correlation is always recommended."
    ))

    return pdf.output(dest="S").encode("latin-1")
